### ISSUE TITLE
Update fails at sudo -u huginn -H bundle exec rake db:migrate RAILS_ENV=production

### ISSUE THREAD

**Issue by johnleeming** [huginn/huginn#2315]
I have had an instance of Huginn running on an AWS t2-micro successfully for several months.  I've updated it a few times but yesterday that failed at sudo -u huginn -H bundle exec rake db:migrate RAILS_ENV=production.  Output of that is below.  Permissions on all subdirectories of /home/huginn/huginn seem correct.  Any clues?

```
:/home/huginn/huginn$ sudo -u huginn -H bundle exec rake db:migrate RAILS_ENV=production --trace
** Invoke db:migrate (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
Errno::EACCES: Permission denied - bs_fetch:atomic_write_cache_file:open
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/compile_cache/iseq.rb:37:in `fetch'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/compile_cache/iseq.rb:37:in `load_iseq'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/application.rb:337:in `require_environment!'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:237:in `block in invoke_prerequisites'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:235:in `each'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:235:in `invoke_prerequisites'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:212:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:237:in `block in invoke_prerequisites'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:235:in `each'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:235:in `invoke_prerequisites'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:212:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bin/rake:22:in `load'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bin/rake:22:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment
```

**Comment by dsander** [comment]
Hi @johnleeming,

that is odd, I just checked the manual update on a VM and it worked without problems. I think there might be a permission issue on your setup, this should fix it:

```
sudo chown -R huginn:huginn /home/huginn/huginn/
```

**Comment by johnleeming** [comment]
Thank you for the very swift response.  That seems to have help teh update complete apparently without errors but I still get a 502 -bad gateway error from Ngnix.  The unicorn.log is full of errors like

`I, [2018-06-18T06:27:23.709470 #4490]  INFO -- : Refreshing Gem list
bundler: failed to load command: unicorn (/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bin/unicorn)
Errno::EACCES: Permission denied - bs_fetch:atomic_write_cache_file:open`

permissions on the unicorn file are:
`-rwxr-xr-x 1 huginn huginn 476 Aug  4  2017 unicorn
`
changing the permissions to 777 doesn't help

that file seems to check the unicorn version then:
`load Gem.bin_path('unicorn', 'unicorn', version)
`
I seem to have unicorn 5.1.0 installed which matches Gemfile.lock

this https://github.com/Shopify/bootsnap/issues/77 suggests issue with bootsnap and to delete bootsnap-compiler-cache directory but that doesn't help

**Comment by johnleeming** [comment]
now up and running!
also deleted and restored contents of /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/compile_cache/

**Comment by johnleeming** [comment]
nb - didn't see @dsander last comment before so haven't done that

**Comment by dsander** [comment]
You deleted `/home/huginn/huginn/tmp/cache/bootsnap-*` and that fixed the problem?

**Comment by mflau** [comment]
same issue 

still get 502 error after change to `require 'bootsnap/setup' if ENV['USER'] != 'root'`
and delete `/home/huginn/huginn/tmp/cache/bootsnap-*`

and `chmod 777 /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/compile_cache/`

unicorn.log:
  ```
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/all.rb:3:in `<main>'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
  /home/huginn/huginn/config/application.rb:3:in `<top (required)>'
  /home/huginn/huginn/config/environment.rb:2:in `require_relative'
  /home/huginn/huginn/config/environment.rb:2:in `<top (required)>'
  config.ru:4:in `require_relative'
  config.ru:4:in `block in <main>'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.4/lib/rack/builder.rb:55:in `instance_eval'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.4/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn.rb:56:in `eval'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn.rb:56:in `block in builder'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:752:in `build_app!'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:129:in `start'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/bin/unicorn:126:in `<top (required)>'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `load'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `<top (required)>'
```

**Comment by johnleeming** [comment]
sorry for the delay in replying, I've been travelling.

I didn't do what @dsander suggested in his second comment but did a bit more poking around and unfortunately didn't record exactly what I did.  As well as deleting the content of: 

`/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/compile_cache/`

I deleted a couple of other bootsnap cache directories including the load_path_cache directory listed in the unicorn log excerpt above.  

I reinstalled bootsnap gem outside huginn and copied the contents of the compile_cache and load_path_cache directories to the relevant places in the huginn/huginn tree.

then ran 

`sudo chown -R huginn:huginn /home/huginn/huginn/`

as suggested by @dsander in his first comment and reran the update process from the step that failed.

**Comment by dsander** [comment]
I did some additional testing on my VM. If I ran `sudo bundle exec rake:production:status` after the update, but before running any task as the `huginn` user I got to the same state you both described. However deleting the cache directory with `sudo rm -rf tmp/cache/bootsnap-*` fixed the problem.

Furthermore the a slightly changed version of my proposed patch worked for me. After applying it command ran as root did not write anything into the cache directory and normal huginn commands (migrations or the server start) worked like expected.

I pushed the change to the repository. Upgrading to that version, deleting the cache directory or `chowning` the home directory to the huginn user should fix it.

@mflau Your exception backtrace is missing the first part, did it start with something like this as well?
```
Errno::EACCES: Permission denied - bs_fetch:atomic_write_cache_file:open
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/compile_cache/iseq.rb:37:in `fetch'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/compile_cache/iseq.rb:37:in `load_iseq'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
```

**Comment by mflau** [comment]
@dsander 

thanks

>  Upgrading to that version, deleting the cache directory

this works

yes, backtrace starts with this:
```
bundler: failed to load command: unicorn (/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bin/unicorn)
Errno::EACCES: Permission denied - bs_fetch:atomic_write_cache_file:open
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/compile_cache/iseq.rb:37:in `fetch'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/compile_cache/iseq.rb:37:in `load_iseq'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/json-1.8.6/lib/json/generic_object.rb:1:in `<main>'
```
and this repeats serveral times:
```
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/compile_cache/iseq.rb:37:in `fetch'
  ...
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/json-1.8.6/lib/json/generic_object.rb:1:in `<main>'
```

**Comment by dsander** [comment]
@mflau Awesome! 
@johnleeming can we close the issue or did the update it not fix your problem?

**Comment by johnleeming** [comment]
I haven't had the opportunity to update again but my hacks have got my
system running so happy for this to be closed.
