### ISSUE TITLE
Cannot deploy production huginn

### ISSUE THREAD

**Issue by luquitared** [huginn/huginn#2320]
I am trying to deploy this on an ubuntu 16.04 server. Every time I pull up the website I get 502 bad gateway. I believe my env file is correct, unicorn conf is correct, and nginx conf is correct. I found another issue that is very similar to mine, https://github.com/huginn/huginn/issues/1442
I went through this thread and have fixed the corresponding mistakes. 

Here is my error for nginx:
`*4 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream,`

For some reason the unicorn.socket file does not get generated when I use:
`sudo bundle exec rake production:export`

Any thoughts?

**Comment by dsander** [comment]
How does your unicorn config look? It should be at `/home/huginn/huginn/config/unicorn.rb`. If that is the same as the example ensure you modified the `Procfile` and [enabled those lines](https://github.com/huginn/huginn/blob/master/Procfile#L24-L25)

Do you get any output in the unicorn log (`/home/huginn/huginn/log/unicorn.log`) or rails production log (`/home/huginn/huginn/log/production.log`)?

**Comment by luquitared** [comment]
Wow! Thank you for the fast reply.

Here is my unicorn config
`wd = File.expand_path(File.join(File.dirname(__FILE__), '..'))

app_path = wd

worker_processes 1
preload_app true
timeout 180
listen "#{wd}/tmp/sockets/unicorn.socket"

working_directory app_path

rails_env = ENV['RAILS_ENV'] || 'production'

# Log everything to one file
stderr_path "log/unicorn.log"
stdout_path "log/unicorn.log"

# Set master PID location
pid "#{wd}/tmp/pids/unicorn.pid"

before_fork do |server, worker|
  ActiveRecord::Base.connection.disconnect!
  old_pid = "#{server.config[:pid]}.oldbin"
  if File.exist?(old_pid) && server.pid != old_pid
    begin
      Process.kill("QUIT", File.read(old_pid).to_i)
    rescue Errno::ENOENT, Errno::ESRCH
      # someone else did our job for us
    end
  end
end

after_fork do |server, worker|
  ActiveRecord::Base.establish_connection
end`

I did modify the Procfile and enabled those two lines.
The output from unicorn log is huge. No output from production. I will paste some of the unicorn here:
`  /home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/application/routes_reloader.rb:57:in `each'
  /home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/application/routes_reloader.rb:57:in `load_paths'
  /home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/application/routes_reloader.rb:20:in `reload!'
  /home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/application.rb:168:in `reload_routes!'
  /home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/devise-4.4.3/lib/devise/rails.rb:17:in `block in <class:Engine>'
  /home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
  /home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
  /home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
  /home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
  /home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:51:in `each'
  /home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
  /home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/application/finisher.rb:68:in `block in <module:Finisher>'
  /home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `instance_exec'
  /home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `run'
  /home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:61:in `block in run_initializers'
  /usr/local/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
  /usr/local/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/local/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/local/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each'
  /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `call'
  /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/local/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
  /usr/local/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
  /home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:60:in `run_initializers'
  /home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/application.rb:361:in `initialize!'
  /home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/railtie.rb:190:in `public_send'
  /home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/railtie.rb:190:in `method_missing'
  /home/huginn/huginn/config/environment.rb:5:in `<top (required)>'
  config.ru:4:in `require_relative'
  config.ru:4:in `block in <main>'
  /home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/rack-2.0.4/lib/rack/builder.rb:55:in `instance_eval'
  /home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/rack-2.0.4/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/unicorn-5.1.0/lib/unicorn.rb:56:in `eval'
  /home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/unicorn-5.1.0/lib/unicorn.rb:56:in `block in builder'
  /home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:752:in `build_app!'
  /home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:129:in `start'
  /home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/unicorn-5.1.0/bin/unicorn:126:in `<top (required)>'
  /home/huginn/huginn/vendor/bundle/ruby/2.5.0/bin/unicorn:23:in `load'
  /home/huginn/huginn/vendor/bundle/ruby/2.5.0/bin/unicorn:23:in `<top (required)>'
I, [2018-06-22T07:46:39.185951 #5395]  INFO -- : Refreshing Gem list`

**Comment by dsander** [comment]
> Wow! Thank you for the fast reply.

You got the timing right, I was just doing my daily checkup on GitHub 😄 

The output in the unicorn log is very verbose, sadly the part you copied is missing the cause for the exception that is probably logged over and over again Can you include more lines from that file either here or in a pastebin?

**Comment by luquitared** [comment]
You are the reason why this community is awesome!!
Hope you are okay with me just uploading the whole file here...
[unicorn.log](https://github.com/huginn/huginn/files/2126781/unicorn.log)

**Comment by dsander** [comment]
That is the relevant line:

`
RuntimeError: YAML syntax error occurred while parsing /home/huginn/huginn/config/database.yml. Please note that YAML must be consistently indented using spaces. Tabs are not allowed. Error: (<unknown>): found character that cannot start any token while scanning for the next token at line 8 column 13
`

Check your `config/database.yml` and make sure you are only using spaces for indentation. If you did not indent to make changes to that file (most configurations don't need it as we have `.env` to configure the database) you can restore the version of the repository with `git checkout config/database.yml`.

**Comment by luquitared** [comment]
I used `git checkout config/database.yml` and I still have the same issue. I never touched the database.yml so I am not sure why that error is being thrown. I checked to make sure they were spaced as well.

**Comment by luquitared** [comment]
Okay I give up trying to install it. Now I cannot remove it... Can you help me completely uninstall? I cannot delete huginn user and it is using a ton of CPU

**Comment by dsander** [comment]
> I used git checkout config/database.yml and I still have the same issue. I never touched the database.yml so I am not sure why that error is being thrown. I checked to make sure they were spaced as well.

It could also be caused by a special character in your `DATABASE_PASSWORD` configuration. Try putting that in quotes like this `DATABASE_PASSWORD="password"`



> Okay I give up trying to install it. Now I cannot remove it... Can you help me completely uninstall? I cannot delete huginn user and it is using a ton of CPU

Do you still have the huginn code installed? `bundle exec rake production:force_stop` should stop the failing processes.

I think stopping the `runit` system service should also stop all huginn processes.

**Comment by luquitared** [comment]
I thought so but something is missing. I get this error:
`Could not locate Gemfile or .bundle/ directory`

**Comment by luquitared** [comment]
I try to install the gems again but nothing. I am not sure how to stop runit. I have tried `sv stop huginn`

**Comment by dsander** [comment]
The service name depends on your Procfile setup, you can find them in `/etc/service/`

```
sudo sv force-stop huginn-jobs-1
sudo sv force-stop huginn-web-1
```

Should work for the default configuration. 

If you want to give the installation another try I recommand your remove the `/home/huginn/huginn` directory and start from [here](https://github.com/huginn/huginn/blob/master/doc/manual/installation.md#5-huginn). I know the installation instructions work, but it's easy to miss a step.

**Comment by luquitared** [comment]
Uninstalled. Thank you for the help! I deployed instead on heroku. Way easier!

**Comment by AntonMyr** [comment]
> That is the relevant line:
> 
> `RuntimeError: YAML syntax error occurred while parsing /home/huginn/huginn/config/database.yml. Please note that YAML must be consistently indented using spaces. Tabs are not allowed. Error: (<unknown>): found character that cannot start any token while scanning for the next token at line 8 column 13`
> 
> Check your `config/database.yml` and make sure you are only using spaces for indentation. If you did not indent to make changes to that file (most configurations don't need it as we have `.env` to configure the database) you can restore the version of the repository with `git checkout config/database.yml`.

I am having this exact issue at the moment, can I get any help with this?

My core issue is that I'm getting `*21 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory)` when running `tail -30 /var/log/nginx/huginn_error.log`.

I tried to reinstall everything, that didn't work.

After that I checked if the unicorn process is running with `ps aux|grep unicorn`, and it was running.

There are no indents in the .env file or the Procfile.

I have not touched the config/database.yml file so it feels weird if that's the issue.

I'm running this on an ubuntu 18.04 server.

**Comment by dsander** [comment]
For the record that is a completely different error 😄 My guess is you missed this step:
```
# Copy the example Unicorn config
sudo -u huginn -H cp config/unicorn.rb.example config/unicorn.rb
```
See [here](https://github.com/huginn/huginn/blob/master/doc/manual/installation.md#nginx-error-log-varlognginxhuginn_errorlog) for reference.

**Comment by AntonMyr** [comment]
I don't quite understand how it's a different error, is it because of the number before `connect()` in the error message?

And I didn't miss that step, the unicorn.rb file is there and I do believe that it's configured correctly. 

Should I just open up a new issue and continue my explanation there?

**Comment by dsander** [comment]
Sorry, I was only looking at the last few messages in this issue, can you post the contents of the other log files mentioned in the troubleshooting section, especially the [unicorn log](https://github.com/huginn/huginn/blob/master/doc/manual/installation.md#unicorn-log-homehuginnhuginnlogunicornlog)?

If you are getting the exact same error message as `YAML syntax error occurred while parsing /home/huginn/huginn/config/database.yml` it is just about fixing the syntax error.
