### ISSUE TITLE
agents keeping event more than defined

### ISSUE THREAD

**Issue by kornflex** [huginn/huginn#2632]
Hi,

I have agents with a "6 hours" keep event value.
But, when I see events stored, I can find events 30 days old.

I tried to change the value, and put it again to force the modification but no purge.

Any ideas ?

thank you

**Comment by dsander** [comment]
Do you have `EVENT_EXPIRATION_CHECK` set in your `.env` configuration? Per default the cleanup should happen every 6 hours. It might be worth a try to restart the Huginn services exclude the possibility  that something is stuck.

**Comment by kornflex** [comment]
Hi !

I have the event expiration check 
I restart huginn and update it with the latest commit. 

Problem still here :/

I will try to put huginn in à container, on a different server.

**Comment by dsander** [comment]
Hmm that is really strange, what is the value of `EVENT_EXPIRATION_CHECK`?

Can you try if this cleans up the Events? Open a rails console on your huginn server

```
cd /home/huginn/huginn
sudo -u huginn -H bundle exec rails console
```

And run this command

```
Event.cleanup_expired!
```

Then check if the Agent still has too many Events.

**Comment by kornflex** [comment]
Hi, 

EVENT_EXPIRATION_CHECK=6h

I launch the command 👍 


Loading production environment (Rails 5.2.2.1)
irb(main):001:0> Event.cleanup_expired!
=> 175
irb(main):002:0> exit

But still the problem :/

I try to delete manually with the webUI on each agent. It succeed but the little green bubble still show 53219 events but they are deleted :/

My DB is corrupted ?

**Comment by dsander** [comment]
I can't really think of what could be causing this.

Now that you deleted can you run the same command again? `Event.cleanup_expired!` updates the database column that is show in the green bubble. If it still not right get the id of the affected Agent from the Agent detail page: `https://yourdomain.com/agents/<the id is shown here>`

Then in the Rails console rune these commands:

```
id = <the id of your agent>

Event.where(agent_id: id).count

Agent.find(id).events_count
```

**Comment by kornflex** [comment]
Thank you for your help. I will try this.

If I doesn't work, is it possible to delete all events from the table events in DB ? I will not crash links between tables ?
I can stop huginn, delete all, start huginn.
I will launch my agents one by one to get their history

**Comment by kornflex** [comment]
Hi,

Loading production environment (Rails 5.2.2.1)
irb(main):001:0> id=376
=> 376
irb(main):002:0> Event.where(agent_id: id).count
=> 3357
irb(main):003:0> Agent.find(id).events_count
=> 53254


53254 is the green bubble and it's wrong.

**Comment by dsander** [comment]
That is odd, the cleanup function must have errored at some point. This in a rails console should fix it:

```
Agent.update_all("events_count = (select count(*) from events where agent_id = agents.id)")
```

**Comment by kornflex** [comment]
Yes, it's OK for the green bubble with your command

But I still have a problem with event memory.
An agent with 6h has 2d events :/

Is it possible to skip or not update my database during an upgrade ?
I can have an old DB schema.

Is it possible to force a check ?

Thank you

**Comment by virtadpt** [comment]
The database is managed with migrations, so you could re-run them if you wanted and it wouldn't hurt anything.  You could do that like this:

```
cd /path/to/huginn
rake db:migrate
```

Do you have a Deduplication Agent in there with a long look-back (500 events or so)?  That might be causing the events to hang around in the database.

**Comment by kornflex** [comment]
Hi,

I think it's solved. I don't run the DB migrate.
I have changed the expiration_event to 1h in the .env file .

I will look in a couple of days to check if it's still OK.

Thank you for your help. I close this topic
